INSERT INTO books VALUES('GEN', 1, 'Genesis', '50', 'ഉല്പത്തി', 'ഉല്പത്തി പുസ്തകം', 1);
INSERT INTO books VALUES('EXO', 2, 'Exodus', '40', 'പുറപ്പാട്', 'പുറപ്പാടു പുസ്തകം', 1);
INSERT INTO books VALUES('LEV', 3, 'Leviticus', '27', 'ലേവ്യപുസ്തകം', 'ലേവ്യപുസ്തകം', 1);
INSERT INTO books VALUES('NUM', 4, 'Numbers', '36', 'സംഖ്യാപുസ്തകം', 'സംഖ്യാപുസ്തകം', 1);
INSERT INTO books VALUES('DEU', 5, 'Deutronomy', '34', 'ആവർത്തനം', 'ആവർത്തന പുസ്തകം', 1);
INSERT INTO books VALUES('JOS', 6, 'Joshua', '24', 'യോശുവ', 'യോശുവ', 1);
INSERT INTO books VALUES('JDG', 7, 'Judges', '21', 'ന്യായാധിപന്മാർ', 'ന്യായാധിപന്മാർ', 1);
INSERT INTO books VALUES('RUT', 8, 'Ruth', '4', 'രൂത്ത്', 'രൂത്ത്', 1);
INSERT INTO books VALUES('1SA', 9, '1 Samuel', '31', '1 ശമൂവേൽ', 'ശമൂവേൽ: ഒന്നാം പുസ്തകം.', 1);
INSERT INTO books VALUES('2SA', 10, '2 Samuel', '24', '2 ശമൂവേൽ', 'ശമൂവേൽ: രണ്ടാം പുസ്തകം.', 1);
INSERT INTO books VALUES('1KI', 11, '1 Kings', '22', '1 രാജാക്കന്മാർ', 'രാജാക്കന്മാർ: ഒന്നാം പുസ്തകം.', 1);
INSERT INTO books VALUES('2KI', 12, '2 Kings', '25', '2 രാജാക്കന്മാർ', 'രാജാക്കന്മാർ: രണ്ടാം പുസ്തകം.', 1);
INSERT INTO books VALUES('1CH', 13, '1 Chronicles', '29', '1 ദിനവൃത്താന്തം', 'ദിനവൃത്താന്തം: ഒന്നാം പുസ്തകം', 1);
INSERT INTO books VALUES('2CH', 14, '2 Chronicles', '36', '2 ദിനവൃത്താന്തം', 'ദിനവൃത്താന്തം: രണ്ടാം പുസ്തകം', 1);
INSERT INTO books VALUES('EZR', 15, 'Ezra', '10', 'എസ്രാ', 'എസ്രാ', 1);
INSERT INTO books VALUES('NEH', 16, 'Nehemieah', '13', 'നെഹെമ്യാവു', 'നെഹെമ്യാവു', 1);
INSERT INTO books VALUES('EST', 17, 'Estar', '10', 'എസ്ഥേർ', 'എസ്ഥേർ', 1);
INSERT INTO books VALUES('JOB', 18, 'Job', '42', 'ഇയ്യോബ്', 'ഇയ്യോബ്', 1);
INSERT INTO books VALUES('PSA', 19, 'Psalms', '150', 'സങ്കീർത്തനങ്ങൾ', 'സങ്കീർത്തനങ്ങൾ', 1);
INSERT INTO books VALUES('PRO', 20, 'Proverbs', '31', 'സദൃശ്യവാക്യങ്ങൾ', 'സദൃശ്യവാക്യങ്ങൾ', 1);
INSERT INTO books VALUES('ECC', 21, 'Ecclesiastes', '12', 'സഭാപ്രസംഗി', 'സഭാപ്രസംഗി', 1);
INSERT INTO books VALUES('SNG', 22, 'Song of songs', '8', 'ഉത്തമ ഗീതം', 'ഉത്തമ ഗീതം', 1);
INSERT INTO books VALUES('ISA', 23, 'Isaiah', '66', 'യെശയ്യാ', 'യെശയ്യാപ്രവാചകൻറെ പുസ്തകം', 1);
INSERT INTO books VALUES('JER', 24, 'Jeremiah', '52', 'യിരേമ്യാവു', 'യിരേമ്യാവു', 1);
INSERT INTO books VALUES('LAM', 25, 'Lamentations', '5', 'വിലാപങ്ങൾ', 'വിലാപങ്ങൾ', 1);
INSERT INTO books VALUES('EZK', 26, 'Ezekiel', '48', 'യേഹേസ്കേൽ', 'യേഹേസ്കേൽ', 1);
INSERT INTO books VALUES('DAN', 27, 'Daniel', '12', 'ദാനീയേൽ', 'ദാനീയേലിൻറെ പുസ്തകം', 1);
INSERT INTO books VALUES('HOS', 28, 'Hosea', '14', 'ഹോശേയ', 'ഹോശേയ', 1);
INSERT INTO books VALUES('JOL', 29, 'Joel', '3', 'യോവേൽ', 'യോവേൽ', 1);
INSERT INTO books VALUES('AMO', 30, 'Amos', '9', 'ആമോസ്', 'ആമോസ്', 1);
INSERT INTO books VALUES('OBD', 31, 'Obadiah', '1', 'ഒബാദ്യാവു', 'ഒബാദ്യാവു', 1);
INSERT INTO books VALUES('JON', 32, 'Jonah', '4', 'യോനാ', 'യോനാ', 1);
INSERT INTO books VALUES('MIC', 33, 'Micah', '7', 'മീഖാ', 'മീഖാ', 1);
INSERT INTO books VALUES('NAM', 34, 'Nahum', '3', 'നഹൂം', 'നഹൂം', 1);
INSERT INTO books VALUES('HAB', 35, 'Habakkuk', '3', 'ഹബക്കൂക്‍', 'ഹബക്കൂക്‍', 1);
INSERT INTO books VALUES('ZEP', 36, 'Zephaniah', '3', 'സെഫന്യാവു', 'സെഫന്യാവു', 1);
INSERT INTO books VALUES('HAG', 37, 'Haggai', '2', 'ഹഗ്ഗായി', 'ഹഗ്ഗായി', 1);
INSERT INTO books VALUES('ZEC', 38, 'Zechariah', '14', 'സെഖർയ്യാവു', 'സെഖർയ്യാവു', 1);
INSERT INTO books VALUES('MAL', 39, 'Malachi', '4', 'മലാഖി', 'മലാഖി', 1);
INSERT INTO books VALUES('MAT', 40, 'Matthew', '28', 'മത്തായി', 'മത്തായി എഴുതിയ സുവിശേഷം', 1);
INSERT INTO books VALUES('MRK', 41, 'Mark', '16', 'മർക്കൊസ്', 'മർക്കൊസ് എഴുതിയ സുവിശേഷം', 1);
INSERT INTO books VALUES('LUK', 42, 'Luke', '24', 'ലൂക്കോസ്', 'ലൂക്കോസ് എഴുതിയ സുവിശേഷം', 1);
INSERT INTO books VALUES('JHN', 43, 'John', '21', 'യോഹന്നാൻ', 'യോഹന്നാൻ എഴുതിയാ സുവിശേഷം', 1);
INSERT INTO books VALUES('ACT', 44, 'Acts', '28', 'പ്രവൃത്തികൾ', 'അപ്പൊസ്തലന്മാരുടെ പ്രവൃത്തികൾ', 1);
INSERT INTO books VALUES('ROM', 45, 'Romans', '16', 'റോമർ', 'റോമർക്ക് എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('1CO', 46, '1 Corinthians', '16', '1 കൊരിന്ത്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് കൊരിന്ത്യര്ക്കു എഴുതിയ ഒന്നാം ലേഖനം.', 1);
INSERT INTO books VALUES('2CO', 47, '2 Corinthians', '13', '2 കൊരിന്ത്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് കൊരിന്ത്യര്ക്കു എഴുതിയ രണ്ടാം ലേഖനം.', 1);
INSERT INTO books VALUES('GAL', 48, 'Galatians ', '6', 'ഗലാത്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് ഗലാത്യര്ക്കു  എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('EPH', 49, 'Ephesians', '6', 'എഫെസ്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് എഫെസ്യര്ക്കു എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('PHP', 50, 'Phillippians', '4', 'ഫിലിപ്പിയർ', 'അപ്പൊസ്തലനായ പൌലൊസ് ഫിലിപ്പിയര്ക്കു  എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('COL', 51, 'Colossians', '4', 'കൊലൊസ്സ്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് കൊലൊസ്സ്യര്ക്കു എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('1TH', 52, '1 Thessalonians', '5', '1 തെസ്സലൊനീക്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് തെസ്സലൊനീക്യര്ക്കു എഴുതിയ ഒന്നാം ലേഖനം.', 1);
INSERT INTO books VALUES('2TH', 53, '2 Thessalonians', '3', '2 തെസ്സലൊനീക്യർ', 'അപ്പൊസ്തലനായ പൌലൊസ് തെസ്സലൊനീക്യര്ക്കു എഴുതിയ രണ്ടാം ലേഖനം.', 1);
INSERT INTO books VALUES('1TI', 54, '1 Timothy', '6', '1 തിമൊഥെയൊസ്', 'അപ്പൊസ്തലനായ പൌലൊസ് തിമൊഥെയൊസിന്നു എഴുതിയ ഒന്നാം ലെഖനം', 1);
INSERT INTO books VALUES('2TI', 55, '2 Timothy', '4', '2 തിമൊഥെയൊസ് ', 'അപ്പൊസ്തലനായ പൌലൊസ് തിമൊഥെയൊസിന്നു എഴുതിയ രണ്ടാം ലെഖനം', 1);
INSERT INTO books VALUES('TIT', 56, 'Titus', '3', 'തീത്തൊസ്', 'അപ്പൊസ്തലനായ പൌലൊസ് തീത്തൊസിന്ൻ എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('PHM', 57, 'Philemon', '1', 'ഫിലേമോൻ', 'അപ്പൊസ്തലനായ പൌലൊസ് ഫിലേമോന്ന്  എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('HEB', 58, 'Hebrews', '13', 'എബ്രായർ', 'എബ്രായര്ക്കു എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('JAS', 59, 'James', '5', 'യാക്കോബ്', 'യാകോബ് എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('1PE', 60, '1 Peter', '5', '1 പത്രൊസ്', 'പത്രൊസ് എഴുതിയ ഒന്നാം ലെഖനം', 1);
INSERT INTO books VALUES('2PE', 61, '2 Peter', '3', '2 പത്രൊസ്', 'പത്രൊസ് എഴുതിയ  രണ്ടാം ലേഖനം', 1);
INSERT INTO books VALUES('1JN', 62, '1 John', '5', '1 യോഹന്നാൻ', 'യോഹന്നാൻ എഴുതിയ ഒന്നാം ലേഖനം', 1);
INSERT INTO books VALUES('2JN', 63, '2 John', '1', '2 യോഹന്നാൻ', 'യോഹന്നാൻ എഴുതിയ രണ്ടാം ലേഖനം', 1);
INSERT INTO books VALUES('3JN', 64, '3 John', '1', '3 യോഹന്നാൻ', 'യോഹന്നാൻ എഴുതിയ മുനാം ലേഖനം', 1);
INSERT INTO books VALUES('JUD', 65, 'Jude', '1', 'യൂദാ', 'യൂദാ എഴുതിയ ലേഖനം', 1);
INSERT INTO books VALUES('REV', 66, 'Revelations', '22', 'വെളിപ്പാടു', 'യോഹന്നാന്നു ഉണ്ടായ വെളിപ്പാടു', 1);
